require "erb"

begin
  require 'jasmine'
  load 'jasmine/tasks/jasmine.rake'
rescue LoadError
  task :jasmine do
    abort "Jasmine is not available. In order to run jasmine, you must: (sudo) gem install jasmine"
  end
end

task :server do
    `thin -R static.ru start`
end

task :get_dependencies do 
    `cp -a ../development/. lib`
    `cp -a ../lib/. lib`
    `cp -a ../release/. lib`
end

# Generate the epub module 
def render_epub_fixed_module_template(templatePath, outputPath)

    # Read each of the library components
    fixed_page_number_logic = File.read('src/models/fixed_page_number_logic.js')
    fixed_page_views = File.read('src/models/fixed_page_views.js')
    fixed_sizing = File.read('src/models/fixed_sizing.js')
    fixed_layout_style = File.read('src/models/fixed_layout_style.js')
    fixed_page_view = File.read('src/views/fixed_page_view.js')
    image_page_view = File.read('src/views/image_page_view.js')
    fixed_pagination_view = File.read('src/views/fixed_pagination_view.js')

    template = File.read(templatePath)
    erb = ERB.new(template)
    
    # Generate library
    File.open(outputPath, "w") do |f|
        f.puts erb.result(binding)
    end
end

desc "render the epub module erb template"
task :gen_module do
    puts "rendering the epub fixed module"

    render_epub_fixed_module_template("src/templates/epub_fixed_module_template.js.erb", "../development/epub_fixed_module.js")
    `cp ../development/epub_fixed_module.js lib/epub_fixed_module.js`
end