task :default => [:copy_dependencies]

module_name = "samples-project-testing"
this_dir = File.dirname(__FILE__)
parent_dir = File.expand_path("..", File.dirname(__FILE__))

lib_dir = this_dir + '/lib'

# Import other dependencies
lib_dependency_filenames = [
  "require.js",
  "jquery-1.9.1.js",
  "json2.js",
  "underscore-1.4.4.js",
  "backbone-0.9.10.js",
  "URIjs",
  "modernizr-2.5.3.min.js",
  "bootstrap.min.js",
  "deflate.js",
  "inflate.js",
  "mime-types.js",
  "zip-ext.js",
  "zip-fs.js",
  "zip.js"
]

module_dependency_names = [
  "readium-js"
]

require 'rake/clean'
CLEAN.include(lib_dir)

directory lib_dir

task :copy_dependencies => ['epub_renderer:gen_module', 'clean', lib_dir] do
  
  puts ":copy_dependencies => #{module_name}"

  # Get all the lib dependencies
  lib_dependency_filenames.each do |filename|
      puts "---> #{filename}"
      `cp -a "#{parent_dir}/epub-modules/lib/#{filename}" "#{this_dir}/lib/#{filename}"`
  end

  # Get all the epub module dependencies
  module_dependency_names.each do |modname|
      puts "---> #{modname}"
      `cp -a "#{parent_dir}/epub-modules/#{modname}/out" "#{this_dir}/lib/#{modname}"`
  end

end

task :server do
    puts `thin -R static.ru start`
end

namespace "epub_renderer" do
  load "#{this_dir}/../epub-modules/readium-js/Rakefile"
end
