task :default => [:copy_dependencies]

def get_module_name
    return "samples-project-testing"
end

def get_this_directory
    return File.dirname(__FILE__)
end

def get_parent_directory
    return File.expand_path("..", File.dirname(__FILE__))
end


library_directory = get_this_directory() + '/lib'

require 'rake/clean'
CLEAN.include(library_directory)


directory library_directory

task :copy_dependencies => [ 'clean', library_directory ] do
  
  module_name = get_module_name()
  puts ":copy_dependencies => #{module_name}"
  
  path_to_this_dir = get_this_directory()

  
  parent_dir = get_parent_directory()

  # Import other dependencies
  lib_dependency_filenames = [
      "require.js",
      "jquery-1.9.1.js",
      "json2.js",
      "underscore-1.4.4.js",
      "backbone-0.9.10.js",
      "URIjs",
      "modernizr-2.5.3.min.js",
      "bootstrap.min.js",
      "deflate.js",
      "inflate.js",
      "mime-types.js",
      "zip-ext.js",
      "zip-fs.js",
      "zip.js"
  ]

  module_dependency_names = [
    "epub-cfi",
    "epub",
    "epub-reader",
    "epub-fetch",
    "epub-reflowable",
    "epub-fixed",
    "epub-parser",
    "epub-ers",
    "simple-readium-js"
  ]

  # Get all the lib dependencies
  lib_dependency_filenames.each do |filename|
      puts "---> #{filename}"
      `cp -a "#{parent_dir}/epub-modules/lib/#{filename}" "#{path_to_this_dir}/lib/#{filename}"`
  end

  # Get all the epub module dependencies
  module_dependency_names.each do |modname|
      puts "---> #{modname}"
      `cp -a "#{parent_dir}/epub-modules/#{modname}/src" "#{path_to_this_dir}/lib/#{modname}"`
  end    
end

task :server do
    puts `thin -R static.ru start`
end
