
begin
  require 'jasmine'
  load 'jasmine/tasks/jasmine.rake'
rescue LoadError
  task :jasmine do
    abort "Jasmine is not available. In order to run jasmine, you must: (sudo) gem install jasmine"
  end
end

task :get_dependencies do
    `cp ../development/epub_fixed_module.js lib/epub_fixed_module.js`
    `cp ../development/epub_reflowable_module.js lib/epub_reflowable_module.js`
    `cp ../development/epub_module.js lib/epub_module.js`
    `cp ../development/epub_parser_module.js lib/epub_parser_module.js`
end

task :server do
    `thin -R view_testing/static.ru start`
end

# Generate the epub module 
def render_epub_reader_module_template(templatePath, outputPath)

    # Read each of the library components
    epub_reader = File.read('src/models/epub_reader.js')
    epub_reader_view = File.read('src/views/epub_reader_view.js')

    template = File.read(templatePath)
    erb = ERB.new(template)
    
    # Generate library
    File.open(outputPath, "w") do |f|
        f.puts erb.result(binding)
    end
end

desc "render the epub reader module erb template"
task :gen_module do
    puts "rendering the epub reader module"
    render_epub_reader_module_template("src/templates/epub_reader_module_template.js.erb", "../development/epub_reader_module.js")
    render_epub_reader_module_template("src/templates/epub_reader_module_template.js.erb", "lib/epub_reader_module.js")
end
