require 'erb'

begin
  require 'jasmine'
  load 'jasmine/tasks/jasmine.rake'
rescue LoadError
  task :jasmine do
    abort "Jasmine is not available. In order to run jasmine, you must: (sudo) gem install jasmine"
  end
end

# Generate the epub module 
def render_epub_module_template(templatePath, outputPath)

    # Read each of the library components
    manifest_item = File.read('src/models/manifest_item.js')
    manifest = File.read('src/models/manifest.js')
    metadata = File.read('src/models/metadata.js')
    page_spread_property = File.read('src/models/page_spread_property.js')
    spine_item = File.read('src/models/spine_item.js')
    spine = File.read('src/models/spine.js')
    package_document = File.read('src/models/package_document.js')

    template = File.read(templatePath)
    erb = ERB.new(template)
    
    # Generate library
    File.open(outputPath, "w") do |f|
        f.puts erb.result(binding)
    end
end

# tasks
desc "render the epub module erb template"
task :gen_module do
    puts "rendering the epub module"
    render_epub_module_template("src/templates/epub_module_template.js.erb", "../development/epub_module.js")
    render_epub_module_template("src/templates/epub_module_template.js.erb", "lib/epub_module.js")
end